# Generated by Django 4.2.3 on 2023-07-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_icon'),
        ('user_profile', '0005_userprofile_liked_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='liked_categories',
            field=models.ManyToManyField(related_name='liked_by', to='category.category'),
        ),
    ]
