# Generated by Django 4.2.3 on 2023-07-13 08:02

from django.db import migrations, models
import poi.models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=poi.models.poi_image_directory_path),
        ),
    ]
