# Generated by Django 4.2.3 on 2023-07-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0002_poi_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='gm_category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='gm_image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='gm_place_id',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='gm_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='poi',
            name='lat',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='lng',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='opening_hours',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='website',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
