version: '3'

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-24-may-2023/luna-project/luna-3:master
    env_file:
      - ./envs/prod.env
    volumes:
      - static_files:/static-files
      - media_files:/media-files
      - build:/frontend/dist
    command: 'sh /scripts/prod.sh'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file:
      - ./envs/prod.env
    volumes:
      - postgres_db:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_files:/static-files
      - media_files:/media-files
      - /etc/letsencrypt:/etc/letsencrypt
      - build:/build

volumes:
  postgres_db:
  media_files:
  static_files:
  build: