# Generated by Django 4.2.3 on 2023-07-13 10:57

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=category.models.category_image_directory_path),
        ),
    ]
