# Generated by Django 4.2.3 on 2023-07-13 08:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transfer', '0001_initial'),
        ('poi', '0002_poi_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, 'POI'), (1, 'Transfer')], default=0)),
                ('start_time', models.TimeField()),
                ('duration', models.TimeField(default=datetime.time(1, 0))),
                ('cost', models.FloatField(default=0.0)),
                ('cost_currency', models.CharField(default='CHF', max_length=3)),
                ('poi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poi.poi')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.transfer')),
            ],
        ),
    ]
