# Generated by Django 4.2.3 on 2023-07-14 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_itinerary_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
