# Generated by Django 4.2.3 on 2023-07-21 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_alter_itinerary_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='start_time',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='transfer_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
