# Generated by Django 4.2.3 on 2023-07-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0005_alter_itinerary_transfer_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='transfer_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
