# Generated by Django 4.2.3 on 2023-07-12 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_registration', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
    ]
