# Generated by Django 4.2.3 on 2023-07-12 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(default='best.motion.ever.group3@gmail.com', max_length=150)),
                ('recipient_list', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('scheduled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
