# Generated by Django 4.2.3 on 2023-07-13 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trip.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=250)),
                ('travel_date', models.DateField()),
                ('total_cost', models.FloatField(default=0.0)),
                ('cost_currency', models.CharField(default='CHF', max_length=3)),
                ('status', models.CharField(default='Planning', max_length=15)),
                ('privacy', models.CharField(choices=[('P', 'private'), ('F', 'friends'), ('E', 'everybody')], default='P', max_length=2)),
                ('trip_image', models.ImageField(blank=True, null=True, upload_to=trip.models.trip_image_directory_path)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to=trip.models.trip_image_directory_path)),
                ('rating_avg', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('mutation_date', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='category.category')),
                ('companions', models.ManyToManyField(related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('liked_by', models.ManyToManyField(related_name='liked_trips', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_trips', to=settings.AUTH_USER_MODEL)),
                ('parent_trip', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='child_trips', to='trip.trip')),
            ],
        ),
    ]
