# Generated by Django 4.2.3 on 2023-07-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_icon'),
        ('trip', '0002_alter_trip_companions_alter_trip_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='categories',
            field=models.ManyToManyField(related_name='trips', to='category.category'),
        ),
    ]
